routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ProductsController@index');

// Route::get('/products', 'ProductsController@index')->name('products.index');
// Route::get('/products/create', 'ProductsController@create')->name('products.create');
// Route::post('/products', 'ProductsController@store')->name('products.store');
// Route::get('/products/{product}', 'ProductsController@show')->name('products.show');
// Route::get('/products/{product}/edit', 'ProductsController@edit')->name('products.edit');
// Route::put('/products/{product}', 'ProductsController@update')->name('products.update');
// Route::delete('/products/{product}', 'ProductsController@destroy')->name('products.destroy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/unauthorized', 'HomeController@unauthorized')->name('unauthorized');

Route::resource('products', 'ProductsController')->only(['show', 'index']);
Route::resource('brands', 'BrandsController')->only(['show']);
Route::resource('colors', 'ColorsController')->only(['show']);

Route::name('panel.')->prefix('panel')->middleware('auth', 'member')->group(function () {
  Route::get('/', 'UserPanelController@show');
  Route::resource('products', 'ProductsController')->except(['show', 'index']);
  Route::resource('users', 'UsersController')->only(['edit', 'update']);
});

Route::name('admin.')->prefix('admin')->namespace('Admin')->middleware('auth')->group(function () {
  // Route::get('/', 'DashboardController@index');
  Route::get('/', 'ProductsController@index')->middleware('moderator');
  Route::resource('colors', 'ColorsController')->except(['show'])->middleware('moderator');
  Route::resource('products', 'ProductsController')->except(['show'])->middleware('moderator');
  // admin only
  Route::resource('users', 'UsersController')->except(['create', 'store'])->middleware('admin');
  Route::resource('permissions', 'PermissionsController')->middleware('admin');
  Route::resource('roles', 'RolesController')->middleware('admin');
  // custom permissions
  Route::resource('brands', 'BrandsController')->except(['show']);
});

Imgfly::routes();

resources/views/admin/home.blade.php
@extends('layouts.admin')

@section ('content')
  <h2>
    Produkty
    <a href="{{ route('panel.products.create') }}" class='btn btn-primary'>Nowy</a>
  </h2>
  <section class='panel-items'>
    @if ($products->count() > 0)
    <table class="table table-bordered table-striped">
      <thead>
        <th>Zdjecie</th>
        <th>Nazwa</th>
        <th>Opis</th>
        <th>Kolory</th>
        <th></th>
      </thead>
      <tbody>
        @foreach ($products as $product)
          <tr>
            <td>
              <a href="{{ route('products.show', $product) }}" class='image-box'>
                <img src=''>
              </a>
            </td>
            <td>
              <a href="{{ route('products.show', $product) }}" class='table-link'>{{ $product->name }}</a>
            </td>
            <td>{{ Str::limit($product->body, $limit = 150, $end = '...') }}</td>
            <td>
              @foreach ( $product->colors as $color )
                <span class="label label-info" style="background-color: {{ $color->hex_value }}">{{ $color->name }}</span>
              @endforeach
            </td>
            <td>
              <a href="{{ route('panel.products.edit', $product) }}" class='label label-info'>Edytuj</a>
              <form action="{{ route('panel.products.destroy', $product) }}" method='POST' class="delete-form">
                @csrf
                @method('DELETE')
                <button type="submit" class="label label-danger">Usuń</button>
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>

    @else
      <p>Brak dodanych produktów</p>
    @endif
  </section>
@endsection

resources/views/admin/no_permission.blade.php
@extends('layouts.admin')

@section('content')
  <section class='text-center'>
    {{ $message }}
  </section>
@endsection