routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ProductsController@index');

// Route::get('/products', 'ProductsController@index')->name('products.index');
// Route::get('/products/create', 'ProductsController@create')->name('products.create');
// Route::post('/products', 'ProductsController@store')->name('products.store');
// Route::get('/products/{product}', 'ProductsController@show')->name('products.show');
// Route::get('/products/{product}/edit', 'ProductsController@edit')->name('products.edit');
// Route::put('/products/{product}', 'ProductsController@update')->name('products.update');
// Route::delete('/products/{product}', 'ProductsController@destroy')->name('products.destroy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/unauthorized', 'HomeController@unauthorized')->name('unauthorized');

Route::resource('products', 'ProductsController')->only(['show', 'index']);
Route::resource('brands', 'BrandsController')->only(['show']);
Route::resource('colors', 'ColorsController')->only(['show']);

Route::name('panel.')->prefix('panel')->middleware('auth', 'member')->group(function () {
  Route::get('/', 'UserPanelController@show');
  Route::resource('products', 'ProductsController')->except(['show', 'index']);
  Route::resource('users', 'UsersController')->only(['edit', 'update']);
});

Route::name('admin.')->prefix('admin')->namespace('Admin')->middleware('auth')->group(function () {
  // Route::get('/', 'DashboardController@index');
  Route::get('/', 'ProductsController@index')->middleware('moderator');
  Route::resource('colors', 'ColorsController')->except(['show'])->middleware('moderator');
  Route::resource('products', 'ProductsController')->except(['show'])->middleware('moderator');
  // admin only
  Route::resource('users', 'UsersController')->except(['create', 'store'])->middleware('admin');
  Route::resource('permissions', 'PermissionsController')->middleware('admin');
  Route::resource('roles', 'RolesController')->middleware('admin');
  // custom permissions
  Route::resource('brands', 'BrandsController')->except(['show']);
});

Imgfly::routes();

app/Color.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    // relationships
    public function products() {
      return $this->belongsToMany(Product::class);
    }

    public function belongsToProduct($product) {
      return $this->products->contains($product->id);
    }

    protected $fillable = ['name', 'hex_value'];
}

app/Http/Controllers/Admin/ColorsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Color;

class ColorsController extends Controller
{

  // public function __construct()
  // {
  //   $this->middleware('moderator'); // moderator or admin
  // }

  public function index() {
    $colors = Color::all();
    return view('admin.colors.index', ['colors' => $colors]);
  }

  public function create() {
    return view('admin.colors.create');
  }

  public function store() {
    $this->validateColor();
    $color = new Color($this->permittedParams());
    $color->save();

    return redirect(route('admin.colors.index'));
  }

  public function edit(Color $color) {
    // $this->authorize('update', $color);
    return view('admin.colors.edit', ['color' => $color]);
  }

  public function update(Color $color) {
    // $this->authorize('update', $color);
    $color->update($this->validateColor());
    return redirect(route('admin.colors.index'));
  }

  public function destroy(Color $color) {
    // $this->authorize('delete', $color);
    $color->delete();
    return redirect(route('admin.colors.index'));
  }

  protected function validateColor() {
    return request()->validate([
      'name' => 'required',
      'hex_value' => 'required'
    ]);
  }

  protected function permittedParams() {
    return request([
      'name',
      'hex_value'
    ]);
  }
}

app/Http/Controllers/ColorsController.php
<?php

namespace App\Http\Controllers;

use App\Color;
use Illuminate\Http\Request;

class ColorsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function show(Color $color)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function edit(Color $color)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Color $color)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function destroy(Color $color)
    {
        //
    }
}

resources/views/admin/colors/create.blade.php
@extends('layouts.admin')

@section ('content')
  <section>
    <h1>Dodaj nowy kolor</h1>
    <form action="{{ route('admin.colors.store') }}" method='POST' class="form-horizontal">
      @csrf
      <div class="form-group @error('name') danger @enderror">
        <label class="col-sm-1 control-label" for="name">Nazwa</label>
        <div class="col-sm-6">
          <input class='form-control' type="text" name="name" id="name" placeholder="Nazwa" value="{{ old('name') }}">
          @error('name')
            <p class="error-field text-danger">{{ $errors->first('name') }}</p>
          @enderror
        </div>
      </div>
      <div class="form-group @error('hex_value') danger @enderror">
        <label class="col-sm-1 control-label" for="hex_value">Wartość HEX</label>
        <div class="col-sm-6">
          <input class='form-control' type="text" name="hex_value" id="hex_value" placeholder="#ffffff" value="{{ old('hex_value') }}">
          @error('hex_value')
            <p class="error-field text-danger">{{ $errors->first('hex_value') }}</p>
          @enderror
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-6 ">
          <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
      </div>
    </form>
  </section>
@endsection

resources/views/admin/colors/edit.blade.php
@extends('layouts.admin')

@section ('content')
  <section>
    <h1>Edytuj: {{ $color->name }}</h1>
    <form action="{{ route('admin.colors.update', $color) }}" method='POST' class="form-horizontal">
      @csrf
      @method('PUT')
      <div class="form-group @error('name') danger @enderror">
        <label class="col-sm-1 control-label" for="name">Nazwa</label>
        <div class="col-sm-6">
          <input class='form-control' type="text" name="name" id="name" placeholder="Nazwa" value="{{ old('name') ? old('name') : $color->name }}">
          @error('name')
            <p class="error-field text-danger">{{ $errors->first('name') }}</p>
          @enderror
        </div>
      </div>
      <div class="form-group @error('hex_value') danger @enderror">
        <label class="col-sm-1 control-label" for="hex_value">Wartość HEX</label>
        <div class="col-sm-6">
          <input class='form-control' type="text" name="hex_value" id="hex_value" placeholder="#ffffff" value="{{ old('hex_value') ? old('hex_value') : $color->hex_value }}">
          @error('hex_value')
            <p class="error-field text-danger">{{ $errors->first('hex_value') }}</p>
          @enderror
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-6 ">
          <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
      </div>
    </form>
  </section>
@endsection

resources/views/admin/colors/index.blade.php
@extends('layouts.admin')

@section ('content')
  <h2>
    Wszystkie kolory
    <a href="{{ route('admin.colors.create') }}" class='btn btn-primary'>Nowy</a>
  </h2>
  <section class='panel-items'>
    @if ($colors->count() > 0)
    <table class="table table-bordered table-striped">
      <thead>
        <th>Kolor</th>
        <th>Nazwa</th>
        <th>Liczba produktów</th>
        <th></th>
      </thead>
      <tbody>
        @foreach ($colors as $color)
          <tr>
            <td>
              <span class='color-box' title="{{ $color->name}}" style="background-color: {{ $color->hex_value}}"></span>
            </td>
            <td>
              {{ $color->name }}
              <br>
              {{ $color->hex_value }}
            </td>
            <td>{{ $color->products()->count() }}</td>
            <td>
              <a href="{{ route('admin.colors.edit', $color) }}" class='label label-info'>Edytuj</a>
              <form action="{{ route('admin.colors.destroy', $color) }}" method='POST' class="delete-form">
                @csrf
                @method('DELETE')
                <button type="submit" class="label label-danger">Usuń</button>
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>

    @else
      <p>Brak dodanych kolorów</p>
    @endif
  </section>
@endsection