routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ProductsController@index');

// Route::get('/products', 'ProductsController@index')->name('products.index');
// Route::get('/products/create', 'ProductsController@create')->name('products.create');
// Route::post('/products', 'ProductsController@store')->name('products.store');
// Route::get('/products/{product}', 'ProductsController@show')->name('products.show');
// Route::get('/products/{product}/edit', 'ProductsController@edit')->name('products.edit');
// Route::put('/products/{product}', 'ProductsController@update')->name('products.update');
// Route::delete('/products/{product}', 'ProductsController@destroy')->name('products.destroy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/unauthorized', 'HomeController@unauthorized')->name('unauthorized');

Route::resource('products', 'ProductsController')->only(['show', 'index']);
Route::resource('brands', 'BrandsController')->only(['show']);
Route::resource('colors', 'ColorsController')->only(['show']);

Route::name('panel.')->prefix('panel')->middleware('auth', 'member')->group(function () {
  Route::get('/', 'UserPanelController@show');
  Route::resource('products', 'ProductsController')->except(['show', 'index']);
  Route::resource('users', 'UsersController')->only(['edit', 'update']);
});

Route::name('admin.')->prefix('admin')->namespace('Admin')->middleware('auth')->group(function () {
  // Route::get('/', 'DashboardController@index');
  Route::get('/', 'ProductsController@index')->middleware('moderator');
  Route::resource('colors', 'ColorsController')->except(['show'])->middleware('moderator');
  Route::resource('products', 'ProductsController')->except(['show'])->middleware('moderator');
  // admin only
  Route::resource('users', 'UsersController')->except(['create', 'store'])->middleware('admin');
  Route::resource('permissions', 'PermissionsController')->middleware('admin');
  Route::resource('roles', 'RolesController')->middleware('admin');
  // custom permissions
  Route::resource('brands', 'BrandsController')->except(['show']);
});

Imgfly::routes();

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
  public function products() {
    return $this->hasMany(Product::class);
  }

  protected $fillable = ['name', 'body'];
}

app/Http/Controllers/Admin/BrandsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\Brand;

class BrandsController extends Controller
{

  // public function __construct()
  // {
  //   $this->middleware('moderator'); // moderator or admin
  // }

  public function index()
  {
    $this->authorize('index', Brand::class);
    $brands = Brand::all();
    return view('admin.brands.index', ['brands' => $brands]);
  }

  public function create()
  {
    $this->authorize('create', Brand::class);
    return view('admin.brands.create');
  }

  public function store(Request $request)
  {
    $this->authorize('create', Brand::class);
    $this->validateBrand();
    $brand = new Brand($this->permittedParams());
    $brand->save();

    return redirect(route('admin.brands.index'));
  }

  public function edit(Brand $brand)
  {
    $this->authorize('edit', Brand::class);
    return view('admin.brands.edit', ['brand' => $brand]);
  }

  public function update(Request $request, Brand $brand)
  {
    $this->authorize('edit', Brand::class);
    $brand->update($this->validateBrand());
    return redirect(route('admin.brands.index'));
  }

  public function destroy(Brand $brand)
  {
    $this->authorize('edit', Brand::class);
    $brand->delete();
    return redirect(route('admin.brands.index'));
  }

  protected function validateBrand() {
    return request()->validate([
      'name' => 'required',
      'body' => 'required'
    ]);
  }

  protected function permittedParams() {
    return request([
      'name',
      'body'
    ]);
  }
}

app/Http/Controllers/BrandsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Brand;

class BrandsController extends Controller
{

  /**
   * Display the specified resource.
   *
   * @param  \App\Brand  $brand
   * @return \Illuminate\Http\Response
   */
  public function show(Brand $brand)
  {
      $products = $brand->products;
      return view('products.index', compact(['brand', 'products']));
  }

}

resources/views/admin/brands/create.blade.php
@extends('layouts.admin')

@section ('content')
  <section>
    <h1>Dodaj nowy kolor</h1>
    <form action="{{ route('admin.brands.store') }}" method='POST' class="form-horizontal">
      @csrf
      <div class="form-group @error('name') danger @enderror">
        <label class="col-sm-1 control-label" for="name">Nazwa</label>
        <div class="col-sm-6">
          <input class='form-control' type="text" name="name" id="name" placeholder="Nazwa" value="{{ old('name') }}">
          @error('name')
            <p class="error-field text-danger">{{ $errors->first('name') }}</p>
          @enderror
        </div>
      </div>
      <div class="form-group @error('body') danger @enderror">
        <label class="col-sm-1 control-label" for="body">Opis</label>
        <div class="col-sm-6">
          <textarea class='form-control' rows='3' name='body' id="body">{{ old('body') }}</textarea>
          @error('body')
            <p class="error-field text-danger">{{ $errors->first('body') }}</p>
          @enderror
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-6 ">
          <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
      </div>
    </form>
  </section>
@endsection

resources/views/admin/brands/edit.blade.php
@extends('layouts.admin')

@section ('content')
  <section>
    <h1>Edytuj: {{ $brand->name }}</h1>
    <form action="{{ route('admin.brands.update', $brand) }}" method='POST' class="form-horizontal">
      @csrf
      @method('PUT')
      <div class="form-group @error('name') danger @enderror">
        <label class="col-sm-1 control-label" for="name">Nazwa</label>
        <div class="col-sm-6">
          <input class='form-control' type="text" name="name" id="name" placeholder="Nazwa" value="{{ old('name') ? old('name') : $brand->name }}">
          @error('name')
            <p class="error-field text-danger">{{ $errors->first('name') }}</p>
          @enderror
        </div>
      </div>
      <div class="form-group @error('body') danger @enderror">
        <label class="col-sm-1 control-label" for="body">Opis</label>
        <div class="col-sm-6">
          <textarea class='form-control' rows='3' name='body' id="body">{{ old('body') ? old('body') : $brand->body }}</textarea>
          @error('body')
            <p class="error-field text-danger">{{ $errors->first('body') }}</p>
          @enderror
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-6 ">
          <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
      </div>
    </form>
  </section>
@endsection

resources/views/admin/brands/index.blade.php
@extends('layouts.admin')

@section ('content')
  <h2>
    Wszystkie margki
    <a href="{{ route('admin.brands.create') }}" class='btn btn-primary'>Nowy</a>
  </h2>
  <section class='panel-items'>
    @if ($brands->count() > 0)
    <table class="table table-bordered table-striped">
      <thead>
        <th>Logo</th>
        <th>Nazwa</th>
        <th>Opis</th>
        <th></th>
      </thead>
      <tbody>
        @foreach ($brands as $brand)
          <tr>
            <td>
              <a href="{{ route('admin.brands.edit', $brand) }}" class='image-box'>
                <img src=''>
              </a>
            </td>
            <td>
              {{ $brand->name }}
            </td>
            <td>{{ Str::limit($brand->body, $limit = 150, $end = '...') }}</td>
            <td>
              <a href="{{ route('admin.brands.edit', $brand) }}" class='label label-info'>Edytuj</a>
              <form action="{{ route('admin.brands.destroy', $brand) }}" method='POST' class="delete-form">
                @csrf
                @method('DELETE')
                <button type="submit" class="label label-danger">Usuń</button>
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>

    @else
      <p>Brak dodanych kolorów</p>
    @endif
  </section>
@endsection