routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ProductsController@index');

// Route::get('/products', 'ProductsController@index')->name('products.index');
// Route::get('/products/create', 'ProductsController@create')->name('products.create');
// Route::post('/products', 'ProductsController@store')->name('products.store');
// Route::get('/products/{product}', 'ProductsController@show')->name('products.show');
// Route::get('/products/{product}/edit', 'ProductsController@edit')->name('products.edit');
// Route::put('/products/{product}', 'ProductsController@update')->name('products.update');
// Route::delete('/products/{product}', 'ProductsController@destroy')->name('products.destroy');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/unauthorized', 'HomeController@unauthorized')->name('unauthorized');

Route::resource('products', 'ProductsController')->only(['show', 'index']);
Route::resource('brands', 'BrandsController')->only(['show']);
Route::resource('colors', 'ColorsController')->only(['show']);

Route::name('panel.')->prefix('panel')->middleware('auth', 'member')->group(function () {
  Route::get('/', 'UserPanelController@show');
  Route::resource('products', 'ProductsController')->except(['show', 'index']);
  Route::resource('users', 'UsersController')->only(['edit', 'update']);
});

Route::name('admin.')->prefix('admin')->namespace('Admin')->middleware('auth')->group(function () {
  // Route::get('/', 'DashboardController@index');
  Route::get('/', 'ProductsController@index')->middleware('moderator');
  Route::resource('colors', 'ColorsController')->except(['show'])->middleware('moderator');
  Route::resource('products', 'ProductsController')->except(['show'])->middleware('moderator');
  // admin only
  Route::resource('users', 'UsersController')->except(['create', 'store'])->middleware('admin');
  Route::resource('permissions', 'PermissionsController')->middleware('admin');
  Route::resource('roles', 'RolesController')->middleware('admin');
  // custom permissions
  Route::resource('brands', 'BrandsController')->except(['show']);
});

Imgfly::routes();

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-inverse shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ route('admin.') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                      <ul class="navbar-nav mr-auto">
                        @auth
                          <li class="nav-item">
                              <a class="nav-link" href="{{ route('admin.products.index') }}">Produkty</a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="{{ route('admin.colors.index') }}">Kolory</a>
                          </li>
                          <li class="nav-item">
                              <a class="nav-link" href="{{ route('admin.brands.index') }}">Marki</a>
                          </li>
                          @if ( Auth::user()->isAdministrator() )
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('admin.users.index') }}">Użytkownicy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('admin.roles.index') }}">Role</a>
                            </li>
                          @endif
                        @endauth
                      </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('products.index') }}">Wróć do serwisu</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
          <div class='container'>
            @yield('content')
          </div>
        </main>
    </div>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @include('layouts.navbar')

        <main class="py-4">
          <div class='container'>
            @yield('content')
          </div>
        </main>
    </div>
</body>
</html>

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('products.index') }}">Produkty</a>
                </li>
                @auth
                  @if ( Auth::user()->isModerator() )
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('admin.') }}">Panel Administracyjny</a>
                    </li>
                  @else
                  <li class="nav-item">
                      <a class="nav-link" href="{{ route('panel.') }}">Panel użytkownika</a>
                  </li>
                  @endif
                @endauth
              </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>